### ISSUE TITLE
[Bug]: When clicking on Response Validations link, page not found appears

### ISSUE THREAD

**Issue by Ahmed-Gomaa22** [ShaftHQ/shafthq.github.io#234]
**Steps**
1. open https://shafthq.github.io
2. from the navbar, click on guide
3. from side-menu, click on actions
4. from actions, click on api
5. from API, click on builder
6. scroll down till Append Default Content Charset To Content Type If Undefined appear
7. click on response validations link

**Actual Result:**
page not found opens
**Expected Result** 
response validation page should be opened

![image](https://github.com/user-attachments/assets/f32ae327-feef-4db5-84e5-a536e6e2dc55)
![image](https://github.com/user-attachments/assets/015427b0-58b2-463f-bd9f-0b979b6dcc7b)

**Comment by AhmdZanoon** [comment]
@Ahmed-Gomaa22 would you like to solve it by yourself ?

**Comment by Ahmed-Gomaa22** [comment]
@AhmdZanoon of course i would 
tell me how

**Comment by AhmdZanoon** [comment]
Dear @Ahmed-Gomaa22 
1. click the edit this page button at the end of the page 
2. You will be redirected to github 
3. Click edit 
4. Scroll down to the lone where the link is broken and update the link to 

https://shafthq.github.io/docs/Keywords/API/Response_Validations

5. Save 
6. You will be told to create new branch as the main branch is protected, click ok 
7. Open the pull request 
8. We will review and merge .
