### ISSUE TITLE
[Bug]: When clicking on  Object validation methods link, page not found appears

### ISSUE THREAD

**Issue by Ahmed-Gomaa22** [ShaftHQ/shafthq.github.io#235]
Steps

1 .open https://shafthq.github.io/
2. from the navbar, click on guide
3. from side-menu, click on actions
4. from actions, click on api
5. from API, click on validations
7. click on Object validation methods link

Actual Result:
page not found opens
Expected Result
Object validation methods page should be opened
![image](https://github.com/user-attachments/assets/ce20a270-b27a-40f7-851a-49270c571e75)
![image](https://github.com/user-attachments/assets/0ddbc0a0-adba-4d97-8626-c559cb69d97a)

**Comment by AhmdZanoon** [comment]
@Ahmed-Gomaa22 would you like to solve this by yourself too?

**Comment by Ahmed-Gomaa22** [comment]
@AhmdZanoon how can i do this?

**Comment by AhmdZanoon** [comment]
@Ahmed-Gomaa22 
1. click the edit this page button at the end of the page 
2. You will be redirected to github 
3. Click edit 
4. Scroll down to the lone where the link is broken and update the link to 

https://shafthq.github.io/docs/Keywords/Validations/Objects

5. Save 
6. You will be told to create new branch as the main branch is protected, click ok 
7. Open the pull request 
8. We will review and merge .
